# Generated by Django 2.2 on 2020-04-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('place', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
